### ISSUE TITLE
Cannot import on Python 3.7

### ISSUE THREAD

**Issue by fluffy-critter** [jehiah/urlnorm#24]
When I try to import urlnorm I get the following:

```
>>> import urlnorm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/fluffy/.local/share/virtualenvs/Authl-bMFs1yld/lib/python3.7/site-packages/urlnorm.py", line 206
    MAX_IP = 0xffffffffL
                       ^
SyntaxError: invalid syntax
```

I have urlnorm 1.1.4 installed from PyPI.

**Comment by ducu** [comment]
Me too, nothing new on this?
